spring.servlet.multipart.max-file-size: 1000MB
spring.servlet.multipart.max-request-size: 1000MB
spring.cloud.gateway.httpclient.codec.multipart.enabled: true
spring.cloud.gateway.httpclient.max-request-size: 1000MB
spring.jpa.properties.hibernate.order_by.default_null_ordering: last
server:
  forward-headers-strategy: framework
spring:
  main:
    allow-bean-definition-overriding: true
  data.rest.base-path: api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/shelf-product?ssl=false
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          queries: true
          ehcache:
            missing_cache_strategy: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  mail:
    smtp:
      timeout: 60000
    host: smtp.mandrillapp.com
    port: 587
    username: IAMAI
    password: '{cipher}6291ca54ce60a94f45cb736e4e4deb6927279f379072a0d16f79f1f66eb1ab2f3bc2c25f51ddb0802e9c90e9027a2c35'
    admin: gladiypavlo@gmail.com
    base-link: https://dashboard.iamaiworld.ai/user/
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    gateway:
      httpclient:
        codec:
          multipart:
            enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    mail:
      enabled: false
springdoc.api-docs.path: /api/v1/profiles/api-doc
logging:
  level:
    com.agenatech: DEBUG
health:
  config:
    enabled: false

server.servlet.encoding.charset: UTF-8
server.servlet.encoding.force-response: true
web.base-url: https://dashboard.iamaiworld.ai/
web.url: https://dashboard.iamaiworld.ai
api.base-url: https://api-dashboard.iamaiworld.ai/api/v1
fileClient.url: https://api-dashboard.iamaiworld.ai
keycloak-client:
  server-url: https://auth-dashboard.iamaiworld.ai/auth
  realm: dashboard
aws.accessKey: '{cipher}36080fc49b5c62ca98b058a594e6a730e3912b3bbce706dc20c7f0f27c15ca58d96ca424599615a121a710743b9baa35'
aws.secretKey: '{cipher}9f38d8429261f5de78bc6ed9e5435d2413ecc5a9689266671c832f742489c0490e623f4197263bfff0045e9b6e1224c0f37a839d0b9c5a6c25c1b27934d86e62'
openai.Key: '{cipher}9ef35231e0ebdfda014311061e689fc648a2d8670d4e04bcf8fdb4263a532626234db68da2bfda86335d3f065abcc941e6e067a8d0dcbd7e70830f78fc43a77b3ed70681def4523a4c10471f094b4831'
stripe.Key: '{cipher}0370b700816407b5614dce89591f41b4c175b626176e9c8a3406a22983d008aedb1fbceadc366e3c0630c034297bbb1e0856aff75b1b7ecf9216ca58ccd6a92503b482d7a3e1d89749e6033e0dc5499456b225b20f7b5eac5b81aea05b6b8c2194ca7fa978daff543a010f9b33115f6cb30c12d5e0ad67b42ad848b54f68ab49'
stripe.Product: '{cipher}cff232055e934fca7aa5c4b53afe887642d5e5c0a30ab9a4bb4db0cc806f20a9ee33b85951f1d8522ff442c06112e551'
stripe.userPrice: '{cipher}cb7785bd159e10910009cd692e03a2d0b91fd45400afef57c9dd94820ce7c0100229a2585fcb7c970de896a154a95647'
sync.url: https://api-preprod.iamaiworld.ai/api/v1/employees/sync
openai.apiUrl: https://api.openai.com/v1/chat/completions
openai.embeddingsApiUrl: https://api.openai.com/v1/embeddings
groq.apiUrl: https://api.groq.com/openai/v1/chat/completions
groq.Key: '{cipher}b5d835f21f3e3dd52466b46f6c54fde678cce81911eae0eb0a5f1fe59f59e86e2ece0403f8f469dce280b4f894569a8a5a7d97a44962a846682a248902b79448884fb7e8ef48774acd3a838206e52fb4'
kleer.api-token: '{cipher}3683d1b78b0f5511b1b7df548bd7ba710d39688365604a2e07998bae858826fa'
kleer.company-id: '{cipher}e9f2c3532106592f2eb6573c19b06d47c39f6edff06b6803c2780abf3c8fdd26'
perplexity.apiUrl: https://api.perplexity.ai/chat/completions
perplexity.Key: '{cipher}33ee757c8f77542cde342abfa75aa0409cfc066e903d9728d457f91776011cd38401f9957407bb533ecf3411b63a94289bd4716bf7345db0e2680c7603b0f33550cee02fb3ac6ef12ff08e8be778a7cf'