spring:
  cloud:
    gateway:
      routes:
        - id: profiles
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/*, /api/v1/employees, /api/v1/employees/*/languages, /api/v1/employees/*/skills/endorsements, /api/v1/employees/*/skills, /api/v1/employees/*/skills/suggested, /api/v1/employees/*/competency, /api/v1/employees/*/assignment, /api/v1/employees/*/personal-details, /api/v1/employees/*/dashboard-layout, /api/v1/employees/*, /api/v1/departments/statistics, /api/v1/employees/*/cv, /api/v1/employees/*/recent-actions, /api/v1/employees/assistant/summarizing, /api/v1/employees/*/company, /api/v1/employees/*/skills/suggested, /api/v1/employees/*/skills/suggested/batch, /api/v1/employees/sync, /api/v1/employees/*/assignments, /api/v1/employees/*/contact, /api/v1/employees/assistant/action
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: projects
          uri: http://profiles
          predicates:
            - Path=/api/v1/role/info/*, /api/v1/projects, /api/v1/projects/names, /api/v1/projects/archived, /api/v1/projects/*, /api/v1/projects/*/team, /api/v1/projects/milestone/*/sub-milestone/*/mark, /api/v1/projects/milestone/*/mark, /api/v1/projects/assigned-team/*/employees, /api/v1/projects/setup, /api/v1/projects/assistant, /api/v1/projects/assistant/summarizing, /api/v1/projects/milestones/assistant/summarizing, /api/v1/projects/roles/assistant, /api/v1/projects/*/team, /api/v1/projects/*/team, /api/v1/projects/team/users, /api/v1/projects/team/matches/additional, /api/v1/projects/*/milestones, /api/v1/projects/assigned-team/*/employees/*, /api/v1/projects/team/*, /api/v1/projects/team/*/*, /api/v1/projects/team/salary/generate, /api/v1/projects/*/past, /api/v1/projects/*/assigned-team, /api/v1/projects/*/milestones, /api/v1/projects/*/stage, /api/v1/projects/*/strategy, /api/v1/projects/*/strategy/highlights, /api/v1/projects/*/strategy/highlights/location, /api/v1/projects/*/collaborators, /api/v1/projects/*/preview, /api/v1/projects/*/feedback-rate, /api/v1/projects/*/endorsement-rate, /api/v1/projects/*/success-rate, /api/v1/projects/*/team/skills, /api/v1/projects/*/involvement-rate, /api/v1/projects/milestones/setup, /api/v1/projects/drafts, /api/v1/projects/drafts/*, /api/v1/projects/*/files, /api/v1/projects/*/files/*, /api/v1/projects/milestones/*/assign, /api/v1/projects/milestones/sub-milestone/*/assign, /api/v1/projects/*/milestones/timeline, /api/v1/projects/pinned, /api/v1/projects/*/pinned, /api/v1/projects/*/relevant-skills, /api/v1/projects/assistant/action, /api/v1/assistant/*, /api/v1/projects/*/transfer, /api/v1/projects/team/matches/*, /api/v1/projects/setup/action, /api/v1/projects/setup/assistant
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: positions
          uri: http://profiles
          predicates:
            - Path=/api/v1/positions, /api/v1/positions/archived, /api/v1/positions/*, /api/v1/positions/*/matched-employees, /api/v1/positions/description, /api/v1/roles/*, /api/v1/roles/*/matched-employees, /api/v1/roles/assistant, /api/v1/roles/assistant/summarizing, /api/v1/roles/assistant/summarizing, /api/v1/positions/assistant, /api/v1/positions/assistant/summarizing, /api/v1/positions/matched-employees, /api/v1/positions/*/match/*, /api/v1/positions/*/matched-employees/*, /api/v1/roles, /api/v1/matrolesches/matched-employees, /api/v1/positions/salary/generate, /api/v1/positions/*/visibility, /api/v1/positions/*/match/*/notify, /api/v1/positions/interested
            - Method=GET,PUT,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: twin-matches
          uri: http://profiles
          predicates:
            - Path=/api/v1/twin-matches, /api/v1/twin-matches/archived, /api/v1/twin-matches/*, /api/v1/twin-matches/generate, /api/v1/twin-matches/matched-employees, /api/v1/twin-matches/*/matched-employees/*
            - Method=GET,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: dream-roles
          uri: http://profiles
          predicates:
            - Path=/api/v1/dream-roles, /api/v1/dream-roles/*, /api/v1/dream-roles/*/interest, /api/v1/dream-roles/interested/*, /api/v1/dream-roles/*/applicants, /api/v1/dream-roles/assistant, /api/v1/dream-roles/assistant/summarizing, /api/v1/dream-roles/*/applications
            - Method=GET,PUT,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: companies
          uri: http://profiles
          predicates:
            - Path=/api/v1/companies/current, /api/v1/admins/roles, /api/v1/admins/*, /api/v1/admins, /api/v1/average-characteristics, /api/v1/gender-balance, /api/v1/age-statistics, /api/v1/name-search, /api/v1/employees, /api/v1/employees/batch, /api/v1/general-dashboard-information, /api/v1/departments, /api/v1/departments/*, /api/v1/employees/roles, /api/v1/employees/total, /api/v1/employees/dynamic-search, /api/v1/recent-actions, /api/v1/aspiration/personal-characteristics, /api/v1/aspiration/employees-age, /api/v1/aspiration/gender-balance, /api/v1/aspiration/departments, /api/v1/aspiration/gender-balance, /api/v1/aspiration/employees-age, /api/v1/aspiration/personal-characteristics, /api/v1/aspiration/employees-age, /api/v1/departments, /api/v1/departments/*, /api/v1/skill-options, /api/v1/skill-options/*, /api/v1/skill-options/batch, /api/v1/skill-options/search, /api/v1/relevant-skills, /api/v1/companies/current/subscription, /api/v1/companies/current/subscription/upgrade, /api/v1/working-format, /api/v1/companies/current/subscription/payment-session, /api/v1/companies/current/subscription/billing, /api/v1/companies/current/subscription/cancel, /api/v1/cv-statistics, /api/v1/profile-filling-percentage, /api/v1/languages-statistics, /api/v1/skills-statistics, /api/v1/companies, /api/v1/companies/current/employees/*, /api/v1/companies/current/assistant, /api/v1/companies/current/tags, /api/v1/companies/*/subscription, /api/v1/companies/*/rename, /api/v1/companies/links, /api/v1/companies/current/overview, /api/v1/ai-agents, /api/v1/skill-options/*/employees/number, /api/v1/companies/*
            - Method=GET,PUT,DELETE,POST,PATCH
          filters:
            - AddPrincipalToPathFilter
        - id: widgets
          uri: http://profiles
          predicates:
            - Path=/api/v1/widgets
            - Method=GET,PUT,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: chats
          uri: http://profiles
          predicates:
            - Path=/api/v1/chats, /api/v1/chats/*, /api/v1/employees/*/chats, /api/v1/chats/*/recent, /api/v1/chats/messages/*, /api/v1/assistant/questions, /api/v1/assistant, /api/v1/assistant/prompts, /api/v1/assistant/models/options
            - Method=GET,PUT,DELETE,POST,PATCH
          filters:
            - AddPrincipalToPathFilter
        - id: feedback
          uri: http://profiles
          predicates:
            - Path=/api/v1/feedback/projects/*/employees/*, /api/v1/feedback/projects/*/employees, /api/v1/feedback/projects/*, /api/v1/feedback/employees/*
            - Method=GET,PUT,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: strategy
          uri: http://profiles
          predicates:
            - Path=/api/v1/strategy, /api/v1/strategy/chats, /api/v1/strategy/chats/*, /api/v1/strategy/projects/suggestion/*, /api/v1/strategy/projects, /api/v1/update-news, /api/v1/news, /api/v1/news/tags, /api/v1/strategy/news/insight, /api/v1/strategy/swot, /api/v1/strategy/chats/{chatId}/highlights, /api/v1/strategy/highlights/location, /api/v1/strategy/insight, /api/v1/strategy/revert, /api/v1/strategy/chats/*/collaborators, /api/v1/strategy/chats/*/collaborators/requests, /api/v1/strategy/created, /api/v1/strategy/*, /api/v1/strategy/*/main, /api/v1/strategy/swot, /api/v1/strategy/chats/*/rename, /api/v1/strategy/*/model/pick, /api/v1/strategy/*/files, /api/v1/strategy/*/files/*, /api/v1/strategy/*/projects/links, /api/v1/strategy/*/projects/options, /api/v1/strategy/*/projects/*, /api/v1/strategy/*/projects, /api/v1/strategies/labs/options/inspired-by, /api/v1/strategies/labs/options/focus-areas, /api/v1/strategies/labs/options/types, /api/v1/strategies/labs/options/keywords, /api/v1/strategies/labs, /api/v1/strategies/labs/*/bets, /api/v1/strategies/labs/*/trends, /api/v1/strategies/labs/*/swot, /api/v1/strategies/labs/*/kpis, /api/v1/strategies/labs/*/pitch, /api/v1/strategies/labs/*/narrative, /api/v1/strategies/labs/*/model, /api/v1/strategies/labs/*/chat, /api/v1/strategies/labs/*/strategic-areas, /api/v1/strategies/labs/*/investment-focuses, /api/v1/strategies/labs/*/data-gaps, /api/v1/strategies/labs/*/data-learning-effects, /api/v1/strategies/labs/*/missions, /api/v1/strategies/labs/*/relevant-skills, /api/v1/strategies/labs/chats, /api/v1/strategies/labs/*/chats, /api/v1/strategies/labs/action, /api/v1/strategies/labs/*/rename, /api/v1/strategies/labs/*/history, /api/v1/strategies/labs/history/*/revert, /api/v1/strategies/labs/*/model/insight, /api/v1/strategies/labs/*/creation-details, /api/v1/strategies/labs/*/model/pick, /api/v1/strategies/labs/*/model/overviews, /api/v1/strategies/labs/*/follow-up, /api/v1/strategies/labs/missions/*, /api/v1/assistant/prompt/optimize, /api/v1/strategies/history, /api/v1/strategies/labs/*/budget, /api/v1/strategies/labs/*/timeline, /api/v1/strategies/labs/*/setup-details, /api/v1/strategies/labs/assistant/prompts, /api/v1/simulate-strategy-lab, /api/v1/simulate-user-fetching, /api/v1/strategies/labs/*, /api/v1/strategies/labs/*/setup, /api/v1/prompts, /api/v1/prompts/*, /api/v1/strategies/labs/setup/assistant, /api/v1/strategies/labs/setup/action, /api/v1/strategies/labs/file, /api/v1/strategies/labs/*/transfer
            - Method=GET,PUT,DELETE,POST,PATCH
          filters:
            - AddPrincipalToPathFilter
        - id: kleer
          uri: http://profiles
          predicates:
            - Path=/api/v1/kleer/transactions, /api/v1/kleer/sync-stripe-balance-transactions
            - Method=GET,POST
          filters:
            - AddPrincipalToPathFilter
        - id: multimedia
          uri: http://multimedia-manager
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia/**
            - Method=GET,DELETE,POST
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
keycloak-client:
  server-url: https://auth-dashboard-dev.iamaiworld.ai/auth
