spring:
  cloud:
    gateway:
      routes:
        - id: profiles
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles, /api/v1/profiles/*/languages, /api/v1/profiles/*/skills/endorsements, /api/v1/employees/*/skills, /api/v1/employees/*/competency, /api/v1/employees/*/assignment, /api/v1/employees/*/personal-details, /api/v1/employees/*/dashboard-layout, /api/v1/profiles/*, /api/v1/departments-by-name, /api/v1/get-departments-names, /api/v1/profiles/*/userCV, /api/v1/profiles/average-profile-percentage
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: projects
          uri: http://profiles
          predicates:
            - Path=/api/v1/role/info/*, /api/v1/projects, /api/v1/projects/archived, /api/v1/projects/*, /api/v1/projects/*/team, /api/v1/projects/milestone/*/sub-milestone/*/mark, /api/v1/projects/milestone/*/mark, /api/v1/projects/assigned-team/*/employees, /api/v1/projects/setup, /api/v1/projects/assistant, /api/v1/projects/assistant/summarizing, /api/v1/projects/milestone/assistant/summarizing, /api/v1/projects/roles/assistant, /api/v1/projects/*/team, /api/v1/projects/*/team, /api/v1/projects/team/users, /api/v1/projects/team/generate-additional-matches, /api/v1/projects/*/milestones, /api/v1/projects/assigned-team/*/employees/*, /api/v1/projects/team/*, /api/v1/projects/team/*/*, /api/v1/projects/team/generate-salary, /api/v1/projects/*/past, /api/v1/projects/*/assigned-team, /api/v1/projects/*/milestones, /api/v1/projects/*/stage
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: positions
          uri: http://profiles
          predicates:
            - Path=/api/v1/positions, /api/v1/positions/archived, /api/v1/positions/*, /api/v1/positions/*/matched-employees, /api/v1/positions/description, /api/v1/matches/*, /api/v1/matches/*/matched-employees, /api/v1/roles/assistant, /api/v1/roles/assistant/summarizing, /api/v1/roles/assistant/summarizing, /api/v1/positions/assistant, /api/v1/positions/assistant/summarizing, /api/v1/positions/matched-employees, /api/v1/positions/*/match/*, /api/v1/positions/*/matched-employees/*, /api/v1/matches, /api/v1/matches/matched-employees, /api/v1/positions/generate-salary, /api/v1/positions/*/visibility
            - Method=GET,PUT,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: twin-matches
          uri: http://profiles
          predicates:
            - Path=/api/v1/twin-matches, /api/v1/twin-matches/archived, /api/v1/twin-matches/*, /api/v1/twin-matches/generate, /api/v1/twin-matches/matched-employees, /api/v1/twin-matches/*/matched-employees/*
            - Method=GET,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: dream-roles
          uri: http://profiles
          predicates:
            - Path=/api/v1/dream-roles, /api/v1/dream-roles/*, /api/v1/dream-roles/*/interest, /api/v1/dream-roles/interested/*, /api/v1/dream-roles/*/applicants, /api/v1/dream-roles/assistant, /api/v1/dream-roles/assistant/summarizing
            - Method=GET,PUT,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: company
          uri: http://profiles
          predicates:
            - Path=/api/v1/company-info, /api/v1/admins/*, /api/v1/admins, /api/v1/average-characteristics, /api/v1/gender-balance, /api/v1/age-statistics, /api/v1/name-search, /api/v1/department-profile/*, /api/v1/department-profiles-upload, /api/v1/general-dashboard-information, /api/v1/department-managers, /api/v1/department, /api/v1/department/*, /api/v1/roles, /api/v1/users-count, /api/v1/employees/dynamic-search, /api/v1/recent-actions, /api/v1/aspiration/personal-characteristics, /api/v1/aspiration/employees-age, /api/v1/aspiration/gender-balance, /api/v1/aspiration/departments, /api/v1/aspiration/gender-balance, /api/v1/aspiration/employees-age, /api/v1/aspiration/personal-characteristics, /api/v1/aspiration/employees-age, /api/v1/departments, /api/v1/skill-options          
            - Method=GET,PUT,DELETE,POST,PATCH
          filters:
            - AddPrincipalToPathFilter
        - id: chats
          uri: http://profiles
          predicates:
            - Path=/api/v1/chats, /api/v1/chats/*, /api/v1/profiles/*/chats, /api/v1/chats/*/recent, /api/v1/chats/messages/*, /api/v1/assistant/questions, /api/v1/assistant, /api/v1/assistant/prompts
            - Method=GET,PUT,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: feedback
          uri: http://profiles
          predicates:
            - Path=/api/v1/feedback/projects/*/employees/*, /api/v1/feedback/projects/*/employees, /api/v1/feedback/projects/*, /api/v1/feedback/employees/*
            - Method=GET,PUT,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: multimedia
          uri: http://multimedia-manager
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia/**
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
keycloak-client:
  server-url: https://auth-dashboard-dev.iamaiworld.ai/auth
